language: php
php:
  - "7.2"

env:
  - JMS_SERIALIZER_VERSION="~1.0"
  - JMS_SERIALIZER_VERSION="~2.0"
  - JMS_SERIALIZER_VERSION="~3.0"

before_script:
  - composer require jms/serializer:${JMS_SERIALIZER_VERSION}
  - composer install --dev
